export { default as PartnerApp } from './PartnerApp';
export { default as PartnerLogin } from './PartnerLogin';
export { default as PartnerDashboard } from './PartnerDashboard';
export { default as PartnerNavBar } from './PartnerNavBar';
export { default as PartnerAgreement } from './PartnerAgreement';
export { default as PartnerAside } from './PartnerAside';
export { default as CongratulationsModal } from './CongratulationsModal';
export { default as ClientReports } from './ClientReports';
export { default as PartnerSystem } from './PartnerSystem';
